package model

import (
	"regexp"
	"strings"
	"time"
)

// DefaultSelfTestMarker opts an unresolved code-review thread into watcher
// feedback when the authenticated viewer placed it in their latest reply or
// opening comment. It is an HTML comment so the marker adds no visible noise to
// a pull request's rendered discussion.
//
// It only ever answers for a comment the viewer wrote themselves, so nobody
// else can use it to change what a reader's watcher does. It exists so that
// the watcher can be tried against a real pull request without waiting for
// somebody to review it. The marker is configurable, and setting it to the
// empty string turns the behaviour off; see home.WatchConfig.
const DefaultSelfTestMarker = "<!-- prutil:test -->"

// AgentCommentMarker identifies an automated reply posted by an agent.
const AgentCommentMarker = "<!-- prutil:agent"

var agentCommitPattern = regexp.MustCompile(`<!--\s*prutil:agent(?::\w+)?\s+commit:([0-9a-fA-F]+)\s*-->`)

// IsAgentComment reports whether a comment was generated by an automated agent.
// It recognizes the HTML tracking comment tag (<!-- prutil:agent commit:... -->)
// as well as common automated response blockquote headers.
func IsAgentComment(body string) bool {
	if strings.Contains(body, AgentCommentMarker) {
		return true
	}
	trimmed := strings.TrimSpace(body)
	return strings.HasPrefix(trimmed, "> automated response from prutil/herdr") ||
		strings.HasPrefix(trimmed, "> automated AI response") ||
		strings.HasPrefix(trimmed, "> automated response")
}

// ExtractAgentCommit returns the commit SHA from an agent tracking comment, if
// present in body.
func ExtractAgentCommit(body string) string {
	matches := agentCommitPattern.FindStringSubmatch(body)
	if len(matches) > 1 {
		return matches[1]
	}
	return ""
}

// ReviewThread is one conversation attached to a pull request, as GitHub's
// review UI groups them: a first comment on a line of the diff and every reply
// under it, resolved or not.
//
// prutil cares about threads rather than comment counts because only a thread
// knows whether it has been dealt with. A pull request's issue-comment total
// moves for chatter that needs no work and stays still for a review comment
// that needs plenty.
type ReviewThread struct {
	ID string
	// Resolved is the reviewer's own mark that the thread is finished with.
	Resolved bool
	// Outdated means the lines the thread was left on have since changed. Such
	// a thread is still feedback: the change may or may not be the answer to it.
	Outdated bool
	// Path is the file the thread hangs off, empty for a thread GitHub could
	// not place.
	Path string
	// URL points at the thread's newest comment, which is what somebody
	// following the link wants to read first.
	URL string

	// Opener is the login that started the thread and Body its opening
	// comment, which together are the context an agent needs.
	Opener   string
	OpenedAt time.Time
	Body     string

	// LatestBy is the login that spoke in the thread last, LatestID that
	// comment's identity and LatestAt its time. A thread whose newest comment
	// is the pull request author's own is a thread they have already answered.
	LatestBy   string
	LatestID   string
	LatestAt   time.Time
	LatestBody string

	// Comments is how many comments the thread holds.
	Comments int
}

// AgentCommit returns the commit SHA recorded in the thread's newest comment if
// it was an automated agent reply carrying a tracking commit tag.
func (t ReviewThread) AgentCommit() string {
	if commit := ExtractAgentCommit(t.LatestBody); commit != "" {
		return commit
	}
	if t.LatestBody == "" {
		return ExtractAgentCommit(t.Body)
	}
	return ""
}

// ReviewFilter configures how review threads are filtered for watcher feedback.
type ReviewFilter struct {
	// Viewer is the authenticated login name of the viewer.
	Viewer string
	// Marker is the optional HTML comment marker for self-test comments.
	Marker string
	// SelfReview treats all unresolved review comments written by the viewer
	// as actionable feedback, as long as they are not automated agent comments.
	SelfReview bool
}

// NeedsAttention reports whether a thread is feedback still waiting on viewer.
// A resolved thread is finished. A thread whose newest comment was posted by
// an automated agent has already been answered. A thread whose last word is the
// viewer's own is otherwise answered unless filter.SelfReview is enabled or
// their latest comment carries filter.Marker.
func (t ReviewThread) NeedsAttention(filter ReviewFilter) bool {
	if t.Resolved {
		return false
	}
	latest := t.LatestBody
	if latest == "" {
		latest = t.Body
	}
	if IsAgentComment(latest) {
		return false
	}
	if filter.Viewer == "" || !strings.EqualFold(t.LatestBy, filter.Viewer) {
		return true
	}
	if filter.SelfReview {
		return true
	}
	return t.selfTestComment(filter.Viewer, filter.Marker)
}

// selfTestComment recognises an explicit watcher test only when the current
// viewer wrote the latest comment carrying marker. Checking only the latest
// comment prevents a thread from remaining permanently open once an agent or
// the viewer replies.
func (t ReviewThread) selfTestComment(viewer, marker string) bool {
	if viewer == "" || marker == "" {
		return false
	}
	if !strings.EqualFold(t.LatestBy, viewer) {
		return false
	}
	if strings.Contains(t.LatestBody, marker) {
		return true
	}
	if t.LatestBody == "" && strings.EqualFold(t.Opener, viewer) && strings.Contains(t.Body, marker) {
		return true
	}
	return false
}

// Feedback selects the threads still waiting on viewer, keeping the order they
// arrived in.
func Feedback(threads []ReviewThread, filter ReviewFilter) []ReviewThread {
	out := make([]ReviewThread, 0, len(threads))
	for _, thread := range threads {
		if thread.NeedsAttention(filter) {
			out = append(out, thread)
		}
	}
	return out
}

// Unhandled selects the threads that have not already been handed to an agent.
// notified maps a thread id to the newest comment it held when it was handed
// over, so a thread that has since been replied to counts as new again.
func Unhandled(threads []ReviewThread, notified map[string]string) []ReviewThread {
	out := make([]ReviewThread, 0, len(threads))
	for _, thread := range threads {
		if seen, ok := notified[thread.ID]; ok && seen == thread.LatestID {
			continue
		}
		out = append(out, thread)
	}
	return out
}

// Digest reduces threads to the thread-id to newest-comment-id mapping the
// watch state remembers.
func Digest(threads []ReviewThread) map[string]string {
	out := make(map[string]string, len(threads))
	for _, thread := range threads {
		out[thread.ID] = thread.LatestID
	}
	return out
}
